apiVersion: sources.eventing.knative.dev/v1alpha1
kind: GitHubSource
metadata:
  name: knative-networking
spec:
  # The types of events to which we are listening.
  eventTypes:
  - pull_request
  - issues

  # The repository to which we are listening.
  # There should be a file like this for each watched repository.
  ownerAndRepository: knative/networking

  # This is the Github access token that is used to register
  # the webhook.
  accessToken:
    secretKeyRef:
      name: github-hook-secret
      key: accessToken

  # This is the secret that is registered alongside the webhook
  # for Github to use to identify itself when calling our endpoint.
  secretToken:
    secretKeyRef:
      name: github-hook-secret
      key: secretToken

  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Broker
    name: default
