apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  generateName: gotool-knative-serving-
  namespace: default
spec:
  source:
    git:
      url: https://github.com/knative/serving.git
      revision: master
  template:
    name: gotool
    arguments:
    - name: ORGANIZATION
      value: knative
    - name: REPOSITORY
      value: serving
