apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  generateName: gotool-knative-build-
spec:
  source:
    git:
      url: https://github.com/knative/build.git
      revision: master
  template:
    name: gotool
    arguments:
    - name: ORGANIZATION
      value: knative
    - name: REPOSITORY
      value: build
