apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: prettier-knative-eventing-contrib-
  namespace: default
spec:
  taskRef:
    name: prettier
  inputs:
    resources:
    - name: source
      resourceSpec:
        type: git
        params:
        - name: url
          value: https://github.com/knative/eventing-contrib.git
    params:
    - name: ORGANIZATION
      value: knative
    - name: REPOSITORY
      value: eventing-contrib
    - name: ASSIGNEE
      value: n3wscott
