apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: reviewrequest-trigger
  namespace: default
spec:
  filter:
    attributes:
      type: dev.knative.source.github.pull_request
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: reviewrequest-bot
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: reviewrequest-bot
  labels:
    serving.knative.dev/visibility: cluster-local
    github: comment
spec:
  template:
    spec:
      containers:
      - image: github.com/mattmoor/knobots/cmd/reviewrequest
