# apiVersion: eventing.knative.dev/v1alpha1
# kind: Trigger
# metadata:
#   name: triage-pr-trigger
#   namespace: default
# spec:
#   filter:
#     attributes:
#       type: dev.knative.source.github.pull_request
#   subscriber:
#     ref:
#       apiVersion: serving.knative.dev/v1
#       kind: Service
#       name: triage-bot
# ---
# apiVersion: eventing.knative.dev/v1alpha1
# kind: Trigger
# metadata:
#   name: triage-issues-trigger
#   namespace: default
# spec:
#   filter:
#     attributes:
#       type: dev.knative.source.github.issues
#   subscriber:
#     ref:
#       apiVersion: serving.knative.dev/v1
#       kind: Service
#       name: triage-bot
# ---
# apiVersion: serving.knative.dev/v1
# kind: Service
# metadata:
#   name: triage-bot
  # labels:
  #   serving.knative.dev/visibility: cluster-local
  #   github: comment
# spec:
#   template:
#     spec:
#       containers:
#       - image: github.com/mattmoor/knobots/cmd/triage
